package renderer;

import primitives.Point;
import primitives.Ray;
import primitives.Vector;
import primitives.Util;
import primitives.Point2D;
import renderer.sampler.Sampler;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a virtual rectangular target area in 3D space.
 * <p>
 * This class is utilized to generate sub-pixel beams for Anti-Aliasing,
 * target area beams for Glossy Reflections/Diffuse Glass, and lens mapping
 * for Depth of Field.
 *
 * @author Elad Zwecher and Benjamin Godfrey
 */
public class BlackBoard {
    /**
     * The upward vector, defining the board's orientation.
     */
    private Vector _vUp = null;
    /**
     * The rightward vector, defining the board's orientation.
     */
    private Vector _vRight = null;
    /**
     * The physical width of the board.
     */
    private double _width;
    /**
     * The physical height of the board.
     */
    private double _height;
    /**
     * The exact center point of the board in 3D space.
     */
    private Point _center;

    /**
     * Constructs a new {@link BlackBoard} acting as a projection area.
     *
     * @param vUp    The upward orientation vector.
     * @param vRight The rightward orientation vector.
     * @param width  The width of the board.
     * @param height The height of the board.
     * @param center The center origin point of the board.
     */
    public BlackBoard(Vector vUp, Vector vRight, double width, double height, Point center){
        _vUp = vUp;
        _vRight = vRight;
        _width = width;
        _height = height;
        _center = center;
    }

    /**
     * A getter for vUp.
     *
     * @return The upward vector of the board.
     */
    public Vector getVUp() {
        return _vUp;
    }

    /**
     * A getter for vRight.
     *
     * @return The rightward vector of the board.
     */
    public Vector getVRight() {
        return _vRight;
    }

    /**
     * A getter for the width of the board.
     *
     * @return The width of the board.
     */
    public double getWidth() {
        return _width;
    }

    /**
     * A getter for the height of the board.
     *
     * @return The height of the board.
     */
    public double getHeight() {
        return _height;
    }

    /**
     * A getter for the center point of the board.
     *
     * @return The center point of the board.
     */
    public Point getCenter() {
        return _center;
    }

    /**
     * Maps a normalized 2D offset coordinate onto the physical 3D board.
     *
     * @param offset The 2D offset generated by a {@link Sampler}.
     * @return The corresponding 3D {@link Point} on the board.
     */
    public Point mapToBoard(Point2D offset){
        Point target = _center;

        if (!Util.isZero(offset.x())) target = target.add(_vRight.scale(offset.x() * _width));
        if (!Util.isZero(offset.y())) target = target.add(_vUp.scale(offset.y() * _height));

        return target;
    }

    /**
     * Generates a beam of rays starting from an origin point and passing through
     * the mathematically generated sample points on the board.
     *
     * @param origin  The origin point where the rays begin.
     * @param sampler The {@link Sampler} responsible for distributing the points.
     * @return A {@link List} of constructed {@link Ray}s.
     */
    public List<Ray> generateBeam(Point origin, Sampler sampler) {
        List<Ray> beam = new ArrayList<>();
        for (Point2D offset : sampler.generateAll()) {
            beam.add(new Ray(origin, mapToBoard(offset).subtract(origin)));
        }
        return beam;
    }
}